My\KanbanBundle\Entity\Card:
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    board_id:
      type: integer 
    lane_id:
      type: integer 
    title:
      type: string
      length: 100
    description:
      type: string
      length: 1000
    estimate:
      type: integer 

